//Mutations
export const STORE_SET_MUTATION = "STORE_SET_MUTATION";
export const COMMENTS_SET_MUTATION = "COMMENTS_SET_MUTATION";
export const COMMENTS_ADD_MUTATION = "COMMENTS_ADD_MUTATION";
export const COMMENTS_UPDATE_MUTATION = "COMMENTS_UPDATE_MUTATION";
export const COMMENTS_DELETE_MUTATION = "COMMENTS_DELETE_MUTATION";

export const USER_SET_MUTATION = "USER_SET_MUTATION";
export const USER_DELETE_MUTATION = "USER_DELETE_MUTATION";
export const USER_UPDATE_MUTATION = "USER_UPDATE_MUTATION";

//Actions
export const LOCALSTORAGE_SET = "LOCALSTORAGE_SET";
export const LOCALSTORAGE_GET = "LOCALSTORAGE_GET";

export const COMMENTS_SET = "COMMENTS_SET";
export const COMMENTS_ADD = "COMMENTS_ADD";
export const COMMENTS_UPDATE = "COMMENTS_UPDATE";
export const COMMENTS_DELETE = "COMMENTS_DELETE";

export const USER_SET = "USER_SET";
export const USER_DELETE = "USER_DELETE";
export const USER_UPDATE = "USER_UPDATE";

export const USER_LOGGIN = "USER_LOGGIN";
