export const SET_MUTATION = "SET_MUTATION";
export const ADD_UPDATE_MUTATION = "ADD_UPDATE_MUTATION";

export const LOCALSTORAGE_SET = "LOCALSTORAGE_SET";
export const LOCALSTORAGE_GET = "LOCALSTORAGE_GET";
